sudo: required
services:
  - docker

before_install: 
  - gem install bundler
  - docker build -t omieecv001/docker-react1 -f Dockerfile.dev .

script: 
  - docker run omieecv001/docker-react1 npm run test -- --coverage